import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Tabs from "@/components/tabs/tabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Memories App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <Header />
        <Tabs />
        {children}
      </body>
    </html>
  );
}
